name: Woofy
on: pull_request_target
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: HarishTeens/woofy-actions@v1.0.2
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

